import type { Metadata } from "next";
import "./globals.css";
import { Rubik as FontMain } from "next/font/google";
import Providers from "@/providers/Providers";

const fontMain = FontMain({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-main",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  return (
    <html lang={locale}>
      <body className={`${fontMain.className}`}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
